name: PHP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    container: srcoder/development-php:php80-fpm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Composer package
        run: composer2 update

      - name: PHPUnit
        run: vendor/bin/phpunit
